<Project>
  <Target Name="BootstrapSamplePackageFeeds" BeforeTargets="Restore">
    <Exec
      WorkingDirectory="$(MSBuildThisFileDirectory)"
      Command='dotnet pack "src/Payload/Payload.csproj" -nologo -c "$(Configuration)"' />

    <Exec
      WorkingDirectory="$(MSBuildThisFileDirectory)"
      Command='dotnet build "tests/ParentPackage/ParentPackage.csproj" -nologo -c "$(Configuration)" -p:RestoreForce=true' />
  </Target>
</Project>
